# Generated by Django 2.2.28 on 2023-06-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchasebilldetails',
            table='transactions_purchasebillsdetails',
        ),
    ]
