# Generated by Django 2.2.28 on 2023-06-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20230618_1226'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchasebilldetails',
            table='transactions_purchasebilldetails',
        ),
    ]
