# Generated by Django 2.2.28 on 2023-06-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20230618_1310'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchasebilldetails',
            table=None,
        ),
    ]
